version: '3.8'

services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: url_analyzer_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: url_analyzer
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Go Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: url_analyzer_server
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=url_analyzer
      - API_KEY=your-secret-api-key
      - GIN_MODE=release
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  # React Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: url_analyzer_client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mysql_data:
